/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.EntityActionType;
import com.mycompany.examproject.Player;
import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class AttackVariantsDialog extends javax.swing.JDialog {

    /**
     * Creates new form AttackVariantsDialog
     */
    
    private EntityActionType attackType;
    private int totalBaseDamage;
    
    public AttackVariantsDialog(java.awt.Frame parent, boolean modal, int totalBaseDamage) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
        initComponents();
        
        if (Player.getInstance().getTotalEquipmentWeight() >= Player.getInstance().getBearableWeight()){
            lightAttackButton.setEnabled(false);
        }
        
        this.totalBaseDamage = totalBaseDamage;
        
        this.setResizable(false);
        
        lightAttackButton.setText("Light attack; damage: " + (int) (totalBaseDamage * 0.8));
        heavyAttackButton.setText("Heavy attack; damage: " + (int) (totalBaseDamage * 1.2));
    }
    
    public EntityActionType getAttackType(){
        return this.attackType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        chooseAttackPanel = new javax.swing.JPanel();
        lightAttackButton = new javax.swing.JButton();
        heavyAttackButton = new javax.swing.JButton();
        chooseAttackLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chooseAttackPanel.setBackground(new java.awt.Color(0, 0, 0));

        lightAttackButton.setBackground(new java.awt.Color(102, 102, 102));
        lightAttackButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        lightAttackButton.setForeground(new java.awt.Color(204, 204, 204));
        lightAttackButton.setText("LIGHT ATTACK");
        lightAttackButton.setBorder(null);
        lightAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightAttackButtonActionPerformed(evt);
            }
        });

        heavyAttackButton.setBackground(new java.awt.Color(102, 102, 102));
        heavyAttackButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        heavyAttackButton.setForeground(new java.awt.Color(204, 204, 204));
        heavyAttackButton.setText("HEAVY ATTACK");
        heavyAttackButton.setBorder(null);
        heavyAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyAttackButtonActionPerformed(evt);
            }
        });

        chooseAttackLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        chooseAttackLabel.setForeground(new java.awt.Color(204, 204, 204));
        chooseAttackLabel.setText("Choose attack type you want to use");

        noteLabel.setFont(new java.awt.Font("Yu Mincho Light", 0, 12)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(204, 204, 204));
        noteLabel.setText("Note that enemies can take more or less damage then shown here, since it depends on weapon you are using!");

        javax.swing.GroupLayout chooseAttackPanelLayout = new javax.swing.GroupLayout(chooseAttackPanel);
        chooseAttackPanel.setLayout(chooseAttackPanelLayout);
        chooseAttackPanelLayout.setHorizontalGroup(
            chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseAttackPanelLayout.createSequentialGroup()
                .addGroup(chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAttackPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lightAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(heavyAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chooseAttackPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(noteLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAttackPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chooseAttackLabel)
                .addGap(85, 85, 85))
        );
        chooseAttackPanelLayout.setVerticalGroup(
            chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAttackPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(chooseAttackLabel)
                .addGap(33, 33, 33)
                .addGroup(chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heavyAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(noteLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseAttackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseAttackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lightAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightAttackButtonActionPerformed
        attackType = EntityActionType.LIGHT_ATTACK;
        this.dispose();
    }//GEN-LAST:event_lightAttackButtonActionPerformed

    private void heavyAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyAttackButtonActionPerformed
        attackType = EntityActionType.HEAVY_ATTACK;
        this.dispose();
    }//GEN-LAST:event_heavyAttackButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseAttackLabel;
    private javax.swing.JPanel chooseAttackPanel;
    private javax.swing.JButton heavyAttackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton lightAttackButton;
    private javax.swing.JLabel noteLabel;
    // End of variables declaration//GEN-END:variables
}