/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.EntityActionType;
import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class AttackVariantsDialog extends javax.swing.JDialog {

    /**
     * Creates new form AttackVariantsDialog
     */
    
    private EntityActionType attackType;
    
    public AttackVariantsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
        initComponents();
    }
    
    public EntityActionType getAttackType(){
        return this.attackType;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        chooseAttackPanel = new javax.swing.JPanel();
        lightAttackButton = new javax.swing.JButton();
        heavyAttackButton = new javax.swing.JButton();
        chooseAttackLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chooseAttackPanel.setBackground(new java.awt.Color(0, 0, 0));

        lightAttackButton.setBackground(new java.awt.Color(102, 102, 102));
        lightAttackButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        lightAttackButton.setForeground(new java.awt.Color(204, 204, 204));
        lightAttackButton.setText("LIGHT ATTACK");
        lightAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightAttackButtonActionPerformed(evt);
            }
        });

        heavyAttackButton.setBackground(new java.awt.Color(102, 102, 102));
        heavyAttackButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        heavyAttackButton.setForeground(new java.awt.Color(204, 204, 204));
        heavyAttackButton.setText("HEAVY ATTACK");
        heavyAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heavyAttackButtonActionPerformed(evt);
            }
        });

        chooseAttackLabel.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        chooseAttackLabel.setForeground(new java.awt.Color(204, 204, 204));
        chooseAttackLabel.setText("Choose attack type you want to use");

        javax.swing.GroupLayout chooseAttackPanelLayout = new javax.swing.GroupLayout(chooseAttackPanel);
        chooseAttackPanel.setLayout(chooseAttackPanelLayout);
        chooseAttackPanelLayout.setHorizontalGroup(
            chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAttackPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(chooseAttackPanelLayout.createSequentialGroup()
                        .addComponent(lightAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heavyAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chooseAttackLabel))
                .addGap(36, 36, 36))
        );
        chooseAttackPanelLayout.setVerticalGroup(
            chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooseAttackPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(chooseAttackLabel)
                .addGap(18, 18, 18)
                .addGroup(chooseAttackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heavyAttackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseAttackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseAttackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lightAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightAttackButtonActionPerformed
        attackType = EntityActionType.LIGHT_ATTACK;
        this.dispose();
    }//GEN-LAST:event_lightAttackButtonActionPerformed

    private void heavyAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heavyAttackButtonActionPerformed
        attackType = EntityActionType.HEAVY_ATTACK;
        this.dispose();
    }//GEN-LAST:event_heavyAttackButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chooseAttackLabel;
    private javax.swing.JPanel chooseAttackPanel;
    private javax.swing.JButton heavyAttackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton lightAttackButton;
    // End of variables declaration//GEN-END:variables
}
