/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.Enemies.enemyStructure.Enemy;
import com.mycompany.examproject.Player;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Arseniy
 */
public class BattleForm extends javax.swing.JFrame {

    /**
     * Creates new form BattleForm
     */
    public BattleForm() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        battleLogArea = new javax.swing.JTextArea();
        enemyIconLabel = new javax.swing.JLabel();
        attackButton = new javax.swing.JButton();
        playerIconLabel = new javax.swing.JLabel();
        playerHpBar = new javax.swing.JProgressBar();
        enemyHpBar = new javax.swing.JProgressBar();
        playerStaminaBar = new javax.swing.JProgressBar();
        inventoryButton = new javax.swing.JButton();
        dodgeButton = new javax.swing.JButton();
        blockButton = new javax.swing.JButton();
        enemyNameLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(966, 580));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        battleLogArea.setEditable(false);
        battleLogArea.setBackground(new java.awt.Color(0, 0, 0));
        battleLogArea.setColumns(20);
        battleLogArea.setFont(new java.awt.Font("Yu Mincho Light", 0, 18)); // NOI18N
        battleLogArea.setForeground(new java.awt.Color(204, 204, 204));
        battleLogArea.setLineWrap(true);
        battleLogArea.setRows(5);
        battleLogArea.setWrapStyleWord(true);
        battleLogArea.setBorder(new AntiqueBorder());
        battleLogArea.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(battleLogArea);

        enemyIconLabel.setBackground(new java.awt.Color(0, 0, 0));

        attackButton.setBackground(new java.awt.Color(51, 51, 51));
        attackButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        attackButton.setForeground(new java.awt.Color(204, 204, 204));
        attackButton.setText("ATTACK");
        attackButton.setBorder(null);
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        playerIconLabel.setBackground(new java.awt.Color(0, 0, 0));
        playerIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 3 июн. 2025 г., 17_05_41 (1).png")); // NOI18N
        playerIconLabel.setText("jLabel1");

        playerHpBar.setForeground(new java.awt.Color(0, 153, 0));

        inventoryButton.setBackground(new java.awt.Color(51, 51, 51));
        inventoryButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(204, 204, 204));
        inventoryButton.setText("Inventory");
        inventoryButton.setBorder(null);

        dodgeButton.setBackground(new java.awt.Color(51, 51, 51));
        dodgeButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        dodgeButton.setForeground(new java.awt.Color(204, 204, 204));
        dodgeButton.setText("dodge");
        dodgeButton.setBorder(null);

        blockButton.setBackground(new java.awt.Color(51, 51, 51));
        blockButton.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        blockButton.setForeground(new java.awt.Color(204, 204, 204));
        blockButton.setText("Block");
        blockButton.setBorder(null);

        enemyNameLabel.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        enemyNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        enemyNameLabel.setText("jLabel1");

        playerNameLabel.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        playerNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        playerNameLabel.setText("You");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dodgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(playerHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(playerStaminaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(playerNameLabel)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enemyIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enemyHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(enemyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playerNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(playerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(playerHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playerStaminaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(enemyNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(enemyIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(enemyHpBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dodgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attackButtonActionPerformed

    public void updateLabels(Player player, Enemy enemy){
        enemyIconLabel.setIcon(new ImageIcon(enemy.getIconSource()));
        enemyNameLabel.setText(enemy.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackButton;
    private javax.swing.JTextArea battleLogArea;
    private javax.swing.JButton blockButton;
    private javax.swing.JButton dodgeButton;
    private javax.swing.JProgressBar enemyHpBar;
    private javax.swing.JLabel enemyIconLabel;
    private javax.swing.JLabel enemyNameLabel;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar playerHpBar;
    private javax.swing.JLabel playerIconLabel;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JProgressBar playerStaminaBar;
    // End of variables declaration//GEN-END:variables
}
