/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 * Диалоговое окно, информирующее игрока о том, что была использована бомба.
 * <p>
 * Наследует {@link javax.swing.JDialog} и отображается в игре, когда игрок применяет
 * бомбу. Содержит сообщение о действии.
 * </p>
 *
 * Пример использования:
 * <pre>
 *     BombUsedDialog dialog = new BombUsedDialog(parentFrame, true);
 *     dialog.setVisible(true);
 * </pre>
 *
 * @author Arseniy
 */
public class BombUsedDialog extends javax.swing.JDialog {

    /**
     * Creates new form LevelUpdateDialog
     */
    public BombUsedDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bombUsedPanel = new javax.swing.JPanel();
        bombUsedLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bombUsedPanel.setBackground(new java.awt.Color(0, 0, 0));

        bombUsedLabel.setFont(new java.awt.Font("Castellar", 0, 20)); // NOI18N
        bombUsedLabel.setForeground(new java.awt.Color(204, 204, 204));
        bombUsedLabel.setText("BOMB USED!");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bombUsedPanelLayout = new javax.swing.GroupLayout(bombUsedPanel);
        bombUsedPanel.setLayout(bombUsedPanelLayout);
        bombUsedPanelLayout.setHorizontalGroup(
            bombUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bombUsedPanelLayout.createSequentialGroup()
                .addGroup(bombUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bombUsedPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bombUsedPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(bombUsedLabel)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        bombUsedPanelLayout.setVerticalGroup(
            bombUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bombUsedPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(bombUsedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bombUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bombUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bombUsedLabel;
    private javax.swing.JPanel bombUsedPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}