/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.Items.Equipment;
import com.mycompany.examproject.Items.Potion;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Arseniy
 */
public class ChestFoundDialog extends javax.swing.JDialog {

    /**
     * Creates new form StashFoundDialog
     */
    public ChestFoundDialog(java.awt.Frame parent, boolean modal, ArrayList<Equipment> foundItems) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.foundItems = foundItems;
        
        updateLabels();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chestPanel = new javax.swing.JPanel();
        lootLabel = new javax.swing.JLabel();
        itemsInChestLabel = new javax.swing.JLabel();
        foundItemsStashPane = new javax.swing.JScrollPane();
        foundItemsList = new javax.swing.JList<>();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chestPanel.setBackground(new java.awt.Color(0, 0, 0));

        lootLabel.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        lootLabel.setForeground(new java.awt.Color(204, 204, 204));
        lootLabel.setText("you found loot!");

        itemsInChestLabel.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        itemsInChestLabel.setForeground(new java.awt.Color(204, 204, 204));
        itemsInChestLabel.setText("ITEMS FOUND IN chest:");

        foundItemsList.setBackground(new java.awt.Color(51, 51, 51));
        foundItemsList.setBorder(null);
        foundItemsList.setFont(new java.awt.Font("Yu Mincho Light", 0, 14)); // NOI18N
        foundItemsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        foundItemsList.setSelectionBackground(new java.awt.Color(102, 0, 153));
        foundItemsStashPane.setViewportView(foundItemsList);

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chestPanelLayout = new javax.swing.GroupLayout(chestPanel);
        chestPanel.setLayout(chestPanelLayout);
        chestPanelLayout.setHorizontalGroup(
            chestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chestPanelLayout.createSequentialGroup()
                .addGroup(chestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chestPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lootLabel))
                    .addGroup(chestPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(chestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemsInChestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(foundItemsStashPane)
                            .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        chestPanelLayout.setVerticalGroup(
            chestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chestPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemsInChestLabel)
                .addGap(18, 18, 18)
                .addComponent(foundItemsStashPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateLabels() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Equipment item : foundItems) {
            model.addElement(item.getName());
        }
        foundItemsList.setModel(model);
        
        foundItemsList.setFocusable(false);
        foundItemsList.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chestPanel;
    private javax.swing.JList<String> foundItemsList;
    private javax.swing.JScrollPane foundItemsStashPane;
    private javax.swing.JLabel itemsInChestLabel;
    private javax.swing.JLabel lootLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Equipment> foundItems;
}