/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.Items.Potion;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 * Диалоговое окно, информирующее игрока о предмете, который выпал с обычного врага.
 * <p>
 * Наследует {@link javax.swing.JDialog} и вызывается в игре, когда после победы над
 * стандартным противником игрок получает награду — зелье или другой предмет.
 * Диалог показывает информацию о найденном предмете и позволяет закрыть окно.
 * </p>
 *
 * Пример использования:
 * <pre>
 *     DefaultEnemyDropDialog dialog = new DefaultEnemyDropDialog(parentFrame, true, drop);
 *     dialog.setVisible(true);
 * </pre>
 *
 * @author Arseniy
 */
public class DefaultEnemyDropDialog extends javax.swing.JDialog {

    /**
     * Creates new form StashFoundDialog
     */
    public DefaultEnemyDropDialog(java.awt.Frame parent, boolean modal, Potion foundItem) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.foundItem = foundItem;
        
        updateLabels();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stashPanel = new javax.swing.JPanel();
        dropLabel1 = new javax.swing.JLabel();
        dropLabel2 = new javax.swing.JLabel();
        dropPane = new javax.swing.JScrollPane();
        foundItemsList = new javax.swing.JList<>();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        stashPanel.setBackground(new java.awt.Color(0, 0, 0));

        dropLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        dropLabel1.setForeground(new java.awt.Color(204, 204, 204));
        dropLabel1.setText("enemy dropped loot!");

        dropLabel2.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        dropLabel2.setForeground(new java.awt.Color(204, 204, 204));
        dropLabel2.setText("items founded in loot:");

        foundItemsList.setBackground(new java.awt.Color(51, 51, 51));
        foundItemsList.setBorder(null);
        foundItemsList.setFont(new java.awt.Font("Yu Mincho Light", 0, 14)); // NOI18N
        foundItemsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        foundItemsList.setSelectionBackground(new java.awt.Color(102, 0, 153));
        dropPane.setViewportView(foundItemsList);

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stashPanelLayout = new javax.swing.GroupLayout(stashPanel);
        stashPanel.setLayout(stashPanelLayout);
        stashPanelLayout.setHorizontalGroup(
            stashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stashPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(dropLabel1)
                .addGap(39, 39, 39))
            .addGroup(stashPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(stashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropPane, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stashPanelLayout.setVerticalGroup(
            stashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stashPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dropLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dropLabel2)
                .addGap(18, 18, 18)
                .addComponent(dropPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateLabels() {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement(foundItem.getName());
        foundItemsList.setModel(model);
        
        foundItemsList.setFocusable(false);
        foundItemsList.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dropLabel1;
    private javax.swing.JLabel dropLabel2;
    private javax.swing.JScrollPane dropPane;
    private javax.swing.JList<String> foundItemsList;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel stashPanel;
    // End of variables declaration//GEN-END:variables
    private Potion foundItem;
}