/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class FightLoseForm extends javax.swing.JFrame {

    /**
     * Creates new form FightLoseForm
     */
    public FightLoseForm() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        losePanel = new javax.swing.JPanel();
        loseLabel = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        loadLastSave = new javax.swing.JButton();
        loseIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        losePanel.setBackground(new java.awt.Color(0, 0, 0));

        loseLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        loseLabel.setForeground(new java.awt.Color(204, 204, 204));
        loseLabel.setText("YOU LOST");

        mainMenuButton.setBackground(new java.awt.Color(102, 102, 102));
        mainMenuButton.setFont(new java.awt.Font("Castellar", 0, 12)); // NOI18N
        mainMenuButton.setForeground(new java.awt.Color(204, 204, 204));
        mainMenuButton.setText("MAIN MENU");
        mainMenuButton.setBorder(null);
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        loadLastSave.setBackground(new java.awt.Color(102, 102, 102));
        loadLastSave.setFont(new java.awt.Font("Castellar", 0, 12)); // NOI18N
        loadLastSave.setForeground(new java.awt.Color(204, 204, 204));
        loadLastSave.setText("LOAD LAST SAVE");
        loadLastSave.setBorder(null);
        loadLastSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadLastSaveActionPerformed(evt);
            }
        });

        loseIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 11 июн. 2025 г., 15_09_46 (1).png")); // NOI18N

        javax.swing.GroupLayout losePanelLayout = new javax.swing.GroupLayout(losePanel);
        losePanel.setLayout(losePanelLayout);
        losePanelLayout.setHorizontalGroup(
            losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePanelLayout.createSequentialGroup()
                .addGroup(losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(losePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadLastSave, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(losePanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(loseIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(losePanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(loseLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        losePanelLayout.setVerticalGroup(
            losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(loseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loseIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(losePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadLastSave, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(losePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(losePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        MainMenuForm mainMenu = new MainMenuForm();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void loadLastSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadLastSaveActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_loadLastSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loadLastSave;
    private javax.swing.JLabel loseIconLabel;
    private javax.swing.JLabel loseLabel;
    private javax.swing.JPanel losePanel;
    private javax.swing.JButton mainMenuButton;
    // End of variables declaration//GEN-END:variables
}