/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class ForewordDialog extends javax.swing.JDialog {

    /**
     * Creates new form forewordDialog
     */
    public ForewordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forewordPanel = new javax.swing.JPanel();
        forwardLabel = new javax.swing.JLabel();
        forewordIconLabel = new javax.swing.JLabel();
        forewordScrollPane = new javax.swing.JScrollPane();
        forewrodTextArea = new javax.swing.JTextArea();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        forewordPanel.setBackground(new java.awt.Color(0, 0, 0));

        forwardLabel.setFont(new java.awt.Font("Castellar", 0, 48)); // NOI18N
        forwardLabel.setForeground(new java.awt.Color(204, 204, 204));
        forwardLabel.setText("foreword");
        forwardLabel.setPreferredSize(new java.awt.Dimension(310, 58));

        forewordIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 15 июн. 2025 г., 17_42_29 (1).png")); // NOI18N
        forewordIconLabel.setBorder(new AntiqueBorder());

        forewordScrollPane.setBackground(new java.awt.Color(0, 0, 0));
        forewordScrollPane.setBorder(null);

        forewrodTextArea.setBackground(new java.awt.Color(0, 0, 0));
        forewrodTextArea.setColumns(20);
        forewrodTextArea.setFont(new java.awt.Font("Yu Mincho Light", 0, 12)); // NOI18N
        forewrodTextArea.setForeground(new java.awt.Color(204, 204, 204));
        forewrodTextArea.setLineWrap(true);
        forewrodTextArea.setRows(5);
        forewrodTextArea.setText("In a forgotten world where cursed bloodlines linger and shadows whisper of ancient kings, a lone knight awakens. His past is lost, his purpose unclear—only the ruined fortress before him remains.\n\nTwisted by a long-broken pact, the castle is alive with corruption. None who enter leave unchanged. Within its walls lie shattered legends, haunted halls, and horrors time tried to erase.\n\nYou are the nameless knight. Each step deeper tests your strength and sanity. In this place, death is not the end—but the beginning.\n\nWelcome to the Abyss.");
        forewrodTextArea.setWrapStyleWord(true);
        forewrodTextArea.setEnabled(false);
        forewrodTextArea.setFocusable(false);
        forewordScrollPane.setViewportView(forewrodTextArea);

        continueButton.setBackground(new java.awt.Color(51, 51, 51));
        continueButton.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        continueButton.setForeground(new java.awt.Color(204, 204, 204));
        continueButton.setText("continue");
        continueButton.setBorder(null);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forewordPanelLayout = new javax.swing.GroupLayout(forewordPanel);
        forewordPanel.setLayout(forewordPanelLayout);
        forewordPanelLayout.setHorizontalGroup(
            forewordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forewordPanelLayout.createSequentialGroup()
                .addGroup(forewordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forewordPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(forewordScrollPane))
                    .addGroup(forewordPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(forewordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(forewordIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forwardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(forewordPanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forewordPanelLayout.setVerticalGroup(
            forewordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forewordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forwardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forewordIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(forewordScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forewordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forewordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_continueButtonActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel forewordIconLabel;
    private javax.swing.JPanel forewordPanel;
    private javax.swing.JScrollPane forewordScrollPane;
    private javax.swing.JTextArea forewrodTextArea;
    private javax.swing.JLabel forwardLabel;
    // End of variables declaration//GEN-END:variables
}
