/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class NotEnoughStaminaDialog extends javax.swing.JDialog {

    /**
     * Creates new form LevelUpdateDialog
     */
    public NotEnoughStaminaDialog(java.awt.Frame parent, boolean modal, int requiredStamina) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.requiredStamina = requiredStamina;
        
        updateLabels();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notEnoughStaminaPanel = new javax.swing.JPanel();
        requiredStaminaAmountLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        requiredStaminaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        notEnoughStaminaPanel.setBackground(new java.awt.Color(0, 0, 0));

        requiredStaminaAmountLabel.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        requiredStaminaAmountLabel.setForeground(new java.awt.Color(204, 204, 204));
        requiredStaminaAmountLabel.setText("REUIRED STAMINA AMOUNT");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        requiredStaminaLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        requiredStaminaLabel.setForeground(new java.awt.Color(204, 204, 204));
        requiredStaminaLabel.setText("NOT ENOUGH STAMINA!");

        javax.swing.GroupLayout notEnoughStaminaPanelLayout = new javax.swing.GroupLayout(notEnoughStaminaPanel);
        notEnoughStaminaPanel.setLayout(notEnoughStaminaPanelLayout);
        notEnoughStaminaPanelLayout.setHorizontalGroup(
            notEnoughStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notEnoughStaminaPanelLayout.createSequentialGroup()
                .addGroup(notEnoughStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notEnoughStaminaPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(notEnoughStaminaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(requiredStaminaLabel))
                    .addGroup(notEnoughStaminaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(requiredStaminaAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notEnoughStaminaPanelLayout.setVerticalGroup(
            notEnoughStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notEnoughStaminaPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(requiredStaminaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requiredStaminaAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notEnoughStaminaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notEnoughStaminaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabels() {
        requiredStaminaAmountLabel.setText("Stamina required: " + requiredStamina + "!");
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notEnoughStaminaPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel requiredStaminaAmountLabel;
    private javax.swing.JLabel requiredStaminaLabel;
    // End of variables declaration//GEN-END:variables
    private int requiredStamina;
}