/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 * Диалоговое окно, информирующее игрока о том, что при поиске или взаимодействии ничего не найдено.
 * <p>
 * Наследует {@link javax.swing.JDialog} и появляется, когда результатом исследования локации ялвяется отсутствие чего-либо в ней.
 * </p>
 *
 * Пример использования:
 * <pre>
 *     NothingFoundDialog dialog = new NothingFoundDialog(parentFrame, true);
 *     dialog.setVisible(true);
 * </pre>
 *
 * @author Arseniy
 */
public class NothingFoundDialog extends javax.swing.JDialog {

    /**
     * Creates new form LevelUpdateDialog
     */
    public NothingFoundDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nothingFoundPanel = new javax.swing.JPanel();
        nothingFoundLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nothingFoundPanel.setBackground(new java.awt.Color(0, 0, 0));

        nothingFoundLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        nothingFoundLabel.setForeground(new java.awt.Color(204, 204, 204));
        nothingFoundLabel.setText("nothing found!");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nothingFoundPanelLayout = new javax.swing.GroupLayout(nothingFoundPanel);
        nothingFoundPanel.setLayout(nothingFoundPanelLayout);
        nothingFoundPanelLayout.setHorizontalGroup(
            nothingFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nothingFoundPanelLayout.createSequentialGroup()
                .addGroup(nothingFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nothingFoundPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nothingFoundPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nothingFoundLabel)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        nothingFoundPanelLayout.setVerticalGroup(
            nothingFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nothingFoundPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nothingFoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nothingFoundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nothingFoundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nothingFoundLabel;
    private javax.swing.JPanel nothingFoundPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}