/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class PlayerStaminaRestoreDialog extends javax.swing.JDialog {

    /**
     * Creates new form playerHealedDialog
     */
    public PlayerStaminaRestoreDialog(java.awt.Frame parent, boolean modal, int newStamina, int staminaBefore, int maxStamina) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        this.newStamina = newStamina;
        this.staminaBefore = staminaBefore;
        this.maxStamina = maxStamina;
        
        updateLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerRestoredStaminaPanel = new javax.swing.JPanel();
        youRestoredStaminaLabel1 = new javax.swing.JLabel();
        youRestoredStaminaLabel2 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        playerRestoredStaminaPanel.setBackground(new java.awt.Color(0, 0, 0));

        youRestoredStaminaLabel1.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        youRestoredStaminaLabel1.setForeground(new java.awt.Color(204, 204, 204));
        youRestoredStaminaLabel1.setText("jLabel1");

        youRestoredStaminaLabel2.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        youRestoredStaminaLabel2.setForeground(new java.awt.Color(204, 204, 204));
        youRestoredStaminaLabel2.setText("jLabel1");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerRestoredStaminaPanelLayout = new javax.swing.GroupLayout(playerRestoredStaminaPanel);
        playerRestoredStaminaPanel.setLayout(playerRestoredStaminaPanelLayout);
        playerRestoredStaminaPanelLayout.setHorizontalGroup(
            playerRestoredStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerRestoredStaminaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerRestoredStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(youRestoredStaminaLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(youRestoredStaminaLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerRestoredStaminaPanelLayout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        playerRestoredStaminaPanelLayout.setVerticalGroup(
            playerRestoredStaminaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerRestoredStaminaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(youRestoredStaminaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(youRestoredStaminaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerRestoredStaminaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerRestoredStaminaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateLabels() {
        youRestoredStaminaLabel1.setText("You regened " + (newStamina - staminaBefore) + " HP!");
        youRestoredStaminaLabel2.setText("Your current health: " + newStamina + "/" + maxStamina);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JPanel playerRestoredStaminaPanel;
    private javax.swing.JLabel youRestoredStaminaLabel1;
    private javax.swing.JLabel youRestoredStaminaLabel2;
    // End of variables declaration//GEN-END:variables
    private int newStamina;
    private int staminaBefore;
    private int maxStamina;
}