/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class PotionAlreadyUsedDialog extends javax.swing.JDialog {

    /**
     * Creates new form PotionAlreadyUsedDialog
     */
    public PotionAlreadyUsedDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potionAlreadyUsedPanel = new javax.swing.JPanel();
        potionAlreadyUsedLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        potionAlreadyUsedPanel.setBackground(new java.awt.Color(0, 0, 0));

        potionAlreadyUsedLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        potionAlreadyUsedLabel.setForeground(new java.awt.Color(204, 204, 204));
        potionAlreadyUsedLabel.setText("ENEMY IS ALREADY POISONED!");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("OK");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout potionAlreadyUsedPanelLayout = new javax.swing.GroupLayout(potionAlreadyUsedPanel);
        potionAlreadyUsedPanel.setLayout(potionAlreadyUsedPanelLayout);
        potionAlreadyUsedPanelLayout.setHorizontalGroup(
            potionAlreadyUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potionAlreadyUsedPanelLayout.createSequentialGroup()
                .addGroup(potionAlreadyUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(potionAlreadyUsedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(potionAlreadyUsedLabel))
                    .addGroup(potionAlreadyUsedPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        potionAlreadyUsedPanelLayout.setVerticalGroup(
            potionAlreadyUsedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potionAlreadyUsedPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(potionAlreadyUsedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potionAlreadyUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potionAlreadyUsedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JLabel potionAlreadyUsedLabel;
    private javax.swing.JPanel potionAlreadyUsedPanel;
    // End of variables declaration//GEN-END:variables
}