/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class StateAndNavigationForm extends javax.swing.JFrame {

    /**
     * Creates new form StateAndNavigationForm
     */
    public StateAndNavigationForm() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerInfoAndBasicButtonsPanel = new javax.swing.JPanel();
        HealthBar = new javax.swing.JProgressBar();
        StaminaBar = new javax.swing.JProgressBar();
        InventoryButton = new javax.swing.JButton();
        ExitToMainMenuButton = new javax.swing.JButton();
        UpgradeMenu = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        PlayerIconLabel = new javax.swing.JLabel();
        LocationInfoPanel = new javax.swing.JPanel();
        LocationImageLabel = new javax.swing.JLabel();
        LocationDescriptionScrollPane = new javax.swing.JScrollPane();
        LocationDescriptionArea = new javax.swing.JTextArea();
        NavigationPanel = new javax.swing.JPanel();
        MapLabel = new javax.swing.JLabel();
        PreviousFloorButton = new javax.swing.JButton();
        NextFloorButton = new javax.swing.JButton();
        CurrentFloorLabel = new javax.swing.JLabel();
        ForwardButton = new javax.swing.JButton();
        ToTheLeftButton = new javax.swing.JButton();
        ToTheRightButton = new javax.swing.JButton();
        BackWardsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        PlayerInfoAndBasicButtonsPanel.setBackground(new java.awt.Color(0, 0, 0));

        InventoryButton.setBackground(new java.awt.Color(51, 51, 51));
        InventoryButton.setForeground(new java.awt.Color(255, 255, 255));
        InventoryButton.setText("Инвентарь");
        InventoryButton.setBorder(null);
        InventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryButtonActionPerformed(evt);
            }
        });

        ExitToMainMenuButton.setBackground(new java.awt.Color(51, 51, 51));
        ExitToMainMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitToMainMenuButton.setText("Выйти в главное меню");
        ExitToMainMenuButton.setBorder(null);
        ExitToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitToMainMenuButtonActionPerformed(evt);
            }
        });

        UpgradeMenu.setBackground(new java.awt.Color(51, 51, 51));
        UpgradeMenu.setForeground(new java.awt.Color(255, 255, 255));
        UpgradeMenu.setText("Меню прокачки");
        UpgradeMenu.setBorder(null);
        UpgradeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpgradeMenuActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(51, 51, 51));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Сохранить прогресс");
        SaveButton.setBorder(null);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        PlayerIconLabel.setBackground(new java.awt.Color(0, 0, 0));
        PlayerIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        PlayerIconLabel.setText("jLabel1");

        javax.swing.GroupLayout PlayerInfoAndBasicButtonsPanelLayout = new javax.swing.GroupLayout(PlayerInfoAndBasicButtonsPanel);
        PlayerInfoAndBasicButtonsPanel.setLayout(PlayerInfoAndBasicButtonsPanelLayout);
        PlayerInfoAndBasicButtonsPanelLayout.setHorizontalGroup(
            PlayerInfoAndBasicButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInfoAndBasicButtonsPanelLayout.createSequentialGroup()
                .addGroup(PlayerInfoAndBasicButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerInfoAndBasicButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(InventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PlayerInfoAndBasicButtonsPanelLayout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(PlayerInfoAndBasicButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UpgradeMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ExitToMainMenuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StaminaBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HealthBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayerInfoAndBasicButtonsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PlayerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PlayerInfoAndBasicButtonsPanelLayout.setVerticalGroup(
            PlayerInfoAndBasicButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerInfoAndBasicButtonsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(HealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StaminaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpgradeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitToMainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LocationInfoPanel.setBackground(new java.awt.Color(0, 0, 0));

        LocationImageLabel.setBackground(new java.awt.Color(0, 0, 0));
        LocationImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        LocationImageLabel.setText("jLabel1");

        LocationDescriptionScrollPane.setBackground(new java.awt.Color(0, 0, 0));

        LocationDescriptionArea.setBackground(new java.awt.Color(0, 0, 0));
        LocationDescriptionArea.setColumns(20);
        LocationDescriptionArea.setForeground(new java.awt.Color(204, 204, 204));
        LocationDescriptionArea.setRows(5);
        LocationDescriptionArea.setBorder(null);
        LocationDescriptionArea.setCaretColor(new java.awt.Color(204, 204, 204));
        LocationDescriptionScrollPane.setViewportView(LocationDescriptionArea);

        javax.swing.GroupLayout LocationInfoPanelLayout = new javax.swing.GroupLayout(LocationInfoPanel);
        LocationInfoPanel.setLayout(LocationInfoPanelLayout);
        LocationInfoPanelLayout.setHorizontalGroup(
            LocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LocationInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LocationImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LocationDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
        LocationInfoPanelLayout.setVerticalGroup(
            LocationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LocationInfoPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(LocationImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LocationDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        NavigationPanel.setBackground(new java.awt.Color(0, 0, 0));

        MapLabel.setBackground(new java.awt.Color(0, 0, 0));
        MapLabel.setForeground(new java.awt.Color(255, 255, 255));
        MapLabel.setText("jLabel1");
        MapLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        PreviousFloorButton.setBackground(new java.awt.Color(51, 51, 51));
        PreviousFloorButton.setForeground(new java.awt.Color(255, 255, 255));
        PreviousFloorButton.setText("Предыдущий этаж");
        PreviousFloorButton.setBorder(null);
        PreviousFloorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousFloorButtonActionPerformed(evt);
            }
        });

        NextFloorButton.setBackground(new java.awt.Color(51, 51, 51));
        NextFloorButton.setForeground(new java.awt.Color(255, 255, 255));
        NextFloorButton.setText("Следующий этаж");
        NextFloorButton.setBorder(null);
        NextFloorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextFloorButtonActionPerformed(evt);
            }
        });

        CurrentFloorLabel.setText("jLabel1");

        ForwardButton.setBackground(new java.awt.Color(51, 51, 51));
        ForwardButton.setForeground(new java.awt.Color(255, 255, 255));
        ForwardButton.setText("🡹");
        ForwardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardButtonActionPerformed(evt);
            }
        });

        ToTheLeftButton.setBackground(new java.awt.Color(51, 51, 51));
        ToTheLeftButton.setForeground(new java.awt.Color(255, 255, 255));
        ToTheLeftButton.setText("🡸");
        ToTheLeftButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ToTheLeftButton.setPreferredSize(new java.awt.Dimension(75, 75));
        ToTheLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToTheLeftButtonActionPerformed(evt);
            }
        });

        ToTheRightButton.setBackground(new java.awt.Color(51, 51, 51));
        ToTheRightButton.setForeground(new java.awt.Color(255, 255, 255));
        ToTheRightButton.setText("🡺");
        ToTheRightButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ToTheRightButton.setPreferredSize(new java.awt.Dimension(75, 75));
        ToTheRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToTheRightButtonActionPerformed(evt);
            }
        });

        BackWardsButton.setBackground(new java.awt.Color(51, 51, 51));
        BackWardsButton.setForeground(new java.awt.Color(255, 255, 255));
        BackWardsButton.setText("🡻");
        BackWardsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackWardsButton.setPreferredSize(new java.awt.Dimension(75, 75));
        BackWardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackWardsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationPanelLayout = new javax.swing.GroupLayout(NavigationPanel);
        NavigationPanel.setLayout(NavigationPanelLayout);
        NavigationPanelLayout.setHorizontalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CurrentFloorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavigationPanelLayout.createSequentialGroup()
                        .addComponent(ToTheLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ToTheRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MapLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavigationPanelLayout.createSequentialGroup()
                        .addComponent(PreviousFloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(NextFloorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackWardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigationPanelLayout.setVerticalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CurrentFloorLabel)
                .addGap(8, 8, 8)
                .addComponent(MapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PreviousFloorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(NextFloorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(ForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToTheLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToTheRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BackWardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PlayerInfoAndBasicButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LocationInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayerInfoAndBasicButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LocationInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitToMainMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitToMainMenuButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void NextFloorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextFloorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextFloorButtonActionPerformed

    private void ToTheLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToTheLeftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToTheLeftButtonActionPerformed

    private void ForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForwardButtonActionPerformed

    private void InventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryButtonActionPerformed

    private void UpgradeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpgradeMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpgradeMenuActionPerformed

    private void PreviousFloorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousFloorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousFloorButtonActionPerformed

    private void ToTheRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToTheRightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToTheRightButtonActionPerformed

    private void BackWardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackWardsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackWardsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackWardsButton;
    private javax.swing.JLabel CurrentFloorLabel;
    private javax.swing.JButton ExitToMainMenuButton;
    private javax.swing.JButton ForwardButton;
    private javax.swing.JProgressBar HealthBar;
    private javax.swing.JButton InventoryButton;
    private javax.swing.JTextArea LocationDescriptionArea;
    private javax.swing.JScrollPane LocationDescriptionScrollPane;
    private javax.swing.JLabel LocationImageLabel;
    private javax.swing.JPanel LocationInfoPanel;
    private javax.swing.JLabel MapLabel;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JButton NextFloorButton;
    private javax.swing.JLabel PlayerIconLabel;
    private javax.swing.JPanel PlayerInfoAndBasicButtonsPanel;
    private javax.swing.JButton PreviousFloorButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JProgressBar StaminaBar;
    private javax.swing.JButton ToTheLeftButton;
    private javax.swing.JButton ToTheRightButton;
    private javax.swing.JButton UpgradeMenu;
    // End of variables declaration//GEN-END:variables
}
