/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Arseniy
 */
public class TrapDialog extends javax.swing.JDialog {

    /**
     * Creates new form TrapDialog
     */
    public TrapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        updateLabel();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trapPanel = new javax.swing.JPanel();
        trapLabel = new javax.swing.JLabel();
        trapImageLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        trapPanel.setBackground(new java.awt.Color(0, 0, 0));

        trapLabel.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        trapLabel.setForeground(new java.awt.Color(204, 204, 204));
        trapLabel.setText("You've fallen into a trap!");

        trapImageLabel.setBorder(new AntiqueBorder());

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trapPanelLayout = new javax.swing.GroupLayout(trapPanel);
        trapPanel.setLayout(trapPanelLayout);
        trapPanelLayout.setHorizontalGroup(
            trapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trapPanelLayout.createSequentialGroup()
                .addGroup(trapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trapPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trapLabel))
                    .addGroup(trapPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(trapImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(trapPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trapPanelLayout.setVerticalGroup(
            trapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trapPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(trapLabel)
                .addGap(18, 18, 18)
                .addComponent(trapImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void updateLabel() {
        String[] iconPaths = {
            "C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 15 июн. 2025 г., 13_02_49.png",
            "C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 15 июн. 2025 г., 13_05_02.png",
            "C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 15 июн. 2025 г., 13_06_03.png"
        };
        int index = (int)(Math.random() * iconPaths.length);
        trapImageLabel.setIcon(new ImageIcon(iconPaths[index]));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JLabel trapImageLabel;
    private javax.swing.JLabel trapLabel;
    private javax.swing.JPanel trapPanel;
    // End of variables declaration//GEN-END:variables

}