/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class WeaponSelectedDialog extends javax.swing.JDialog {

    /**
     * Creates new form LevelUpdateDialog
     */
    public WeaponSelectedDialog(java.awt.Frame parent, boolean modal, String name) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.name = name;
        
        updateLabels();
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weaponSelectedPanel = new javax.swing.JPanel();
        weaponSelectedNameLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        weaponSelectedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        weaponSelectedPanel.setBackground(new java.awt.Color(0, 0, 0));

        weaponSelectedNameLabel.setFont(new java.awt.Font("Castellar", 0, 16)); // NOI18N
        weaponSelectedNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        weaponSelectedNameLabel.setText("WEAPON NAME");

        okButton.setBackground(new java.awt.Color(102, 102, 102));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        weaponSelectedLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        weaponSelectedLabel.setForeground(new java.awt.Color(204, 204, 204));
        weaponSelectedLabel.setText("WEAPON SELECTED:");

        javax.swing.GroupLayout weaponSelectedPanelLayout = new javax.swing.GroupLayout(weaponSelectedPanel);
        weaponSelectedPanel.setLayout(weaponSelectedPanelLayout);
        weaponSelectedPanelLayout.setHorizontalGroup(
            weaponSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponSelectedPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(weaponSelectedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weaponSelectedLabel))
            .addGroup(weaponSelectedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weaponSelectedNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        weaponSelectedPanelLayout.setVerticalGroup(
            weaponSelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponSelectedPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(weaponSelectedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weaponSelectedNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weaponSelectedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weaponSelectedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateLabels() {
        weaponSelectedNameLabel.setText(name + "!");
    }
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JLabel weaponSelectedLabel;
    private javax.swing.JLabel weaponSelectedNameLabel;
    private javax.swing.JPanel weaponSelectedPanel;
    // End of variables declaration//GEN-END:variables
    private String name;
}