/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import java.awt.Color;

/**
 *
 * @author Arseniy
 */
public class YouBeatTheGameDialog extends javax.swing.JDialog {

    /**
     * Creates new form YouBeatTheGameDialog
     */
    public YouBeatTheGameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameBeatPanel = new javax.swing.JPanel();
        congratulationsLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        gameBeatIconLabel = new javax.swing.JLabel();
        gameBeatPane = new javax.swing.JScrollPane();
        gameBeatArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        gameBeatPanel.setBackground(new java.awt.Color(0, 0, 0));

        congratulationsLabel.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        congratulationsLabel.setForeground(new java.awt.Color(204, 204, 204));
        congratulationsLabel.setText("congratulations!");

        okButton.setBackground(new java.awt.Color(51, 51, 51));
        okButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(204, 204, 204));
        okButton.setText("ok");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        gameBeatIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image 16 июн. 2025 г., 10_20_27 (1).png"))); // NOI18N
        gameBeatIconLabel.setBorder(new AntiqueBorder());

        gameBeatPane.setBorder(new AntiqueBorder());

        gameBeatArea.setBackground(new java.awt.Color(0, 0, 0));
        gameBeatArea.setColumns(20);
        gameBeatArea.setFont(new java.awt.Font("Yu Mincho Light", 0, 12)); // NOI18N
        gameBeatArea.setForeground(new java.awt.Color(204, 204, 204));
        gameBeatArea.setLineWrap(true);
        gameBeatArea.setRows(5);
        gameBeatArea.setText("Epilogue: Ash Reigns Quiet\n\nIt is done.\nThe blade rests, its edge dulled by trials unspoken. You, nameless and forgotten, have walked through ruin, bled through shadow, and silenced the cursed heart of the castle.\nNo glory awaits. No cheers echo. Only the wind, sifting through broken stone.\nThe monsters lie still. The dead, truly dead. The rot recedes.\nYou did not win—you endured. Where others fell, you stood. Every soul earned was pain rememered, not honor gained.\nThe fire fades. The gate stands open.\nYou may leave. Or remain, a warden of silence.\n\nThe curse is broken.\n\nBut something stirs in the dark... still waiting...");
        gameBeatArea.setWrapStyleWord(true);
        gameBeatArea.setBorder(null);
        gameBeatPane.setViewportView(gameBeatArea);

        javax.swing.GroupLayout gameBeatPanelLayout = new javax.swing.GroupLayout(gameBeatPanel);
        gameBeatPanel.setLayout(gameBeatPanelLayout);
        gameBeatPanelLayout.setHorizontalGroup(
            gameBeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBeatPanelLayout.createSequentialGroup()
                .addGroup(gameBeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameBeatPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(gameBeatIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gameBeatPane))
                    .addGroup(gameBeatPanelLayout.createSequentialGroup()
                        .addGroup(gameBeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gameBeatPanelLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(congratulationsLabel))
                            .addGroup(gameBeatPanelLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gameBeatPanelLayout.setVerticalGroup(
            gameBeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameBeatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(congratulationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameBeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gameBeatIconLabel)
                    .addComponent(gameBeatPane, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameBeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameBeatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel congratulationsLabel;
    private javax.swing.JTextArea gameBeatArea;
    private javax.swing.JLabel gameBeatIconLabel;
    private javax.swing.JScrollPane gameBeatPane;
    private javax.swing.JPanel gameBeatPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
