/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.examproject.GUI;

import com.mycompany.examproject.GUIandLogicIntermediary;
import static com.mycompany.examproject.GUIandLogicIntermediary.processFoundedItemsInChest;
import com.mycompany.examproject.Items.Equipment;
import com.mycompany.examproject.Player;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Arseniy
 */
public class YouFoundChestDialog extends javax.swing.JDialog {

    /**
     * Creates new form YouFoundChestDialog
     */
    public YouFoundChestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.BLACK);
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chestFoundPanel = new javax.swing.JPanel();
        chestFoundLabel = new javax.swing.JLabel();
        chestIconLabel = new javax.swing.JLabel();
        passChestButton = new javax.swing.JButton();
        openChestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chestFoundPanel.setBackground(new java.awt.Color(0, 0, 0));

        chestFoundLabel.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        chestFoundLabel.setForeground(new java.awt.Color(204, 204, 204));
        chestFoundLabel.setText("you found chest!");
        chestFoundLabel.setPreferredSize(new java.awt.Dimension(200, 22));

        chestIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Arseniy\\Downloads\\ChatGPT Image 15 июн. 2025 г., 15_17_56 (1).png")); // NOI18N
        chestIconLabel.setText("jLabel2");

        passChestButton.setBackground(new java.awt.Color(102, 102, 102));
        passChestButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        passChestButton.setForeground(new java.awt.Color(204, 204, 204));
        passChestButton.setText("pass by");
        passChestButton.setBorder(null);
        passChestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passChestButtonActionPerformed(evt);
            }
        });

        openChestButton.setBackground(new java.awt.Color(102, 102, 102));
        openChestButton.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        openChestButton.setForeground(new java.awt.Color(204, 204, 204));
        openChestButton.setText("open");
        openChestButton.setBorder(null);
        openChestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openChestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chestFoundPanelLayout = new javax.swing.GroupLayout(chestFoundPanel);
        chestFoundPanel.setLayout(chestFoundPanelLayout);
        chestFoundPanelLayout.setHorizontalGroup(
            chestFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chestFoundPanelLayout.createSequentialGroup()
                .addGroup(chestFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chestFoundPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(chestFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chestFoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chestIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(chestFoundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(passChestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(openChestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chestFoundPanelLayout.setVerticalGroup(
            chestFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chestFoundPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(chestFoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chestIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(chestFoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passChestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(openChestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chestFoundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chestFoundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passChestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passChestButtonActionPerformed
        this.dispose();
        GUIandLogicIntermediary.showNavigationForm();
    }//GEN-LAST:event_passChestButtonActionPerformed

    private void openChestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openChestButtonActionPerformed
        double subRand2 = Math.random();
        if (subRand2 < 0.5){
            this.dispose();
            int floorNum = Player.getInstance().getCurrentRoom().getFloor();
            ArrayList<Equipment> foundItems = processFoundedItemsInChest(floorNum);
            ChestFoundDialog chestFoundDialog = new ChestFoundDialog(null, true, foundItems);
            chestFoundDialog.setVisible(true);
                
            GUIandLogicIntermediary.showNavigationForm();
        } else if (subRand2 < 0.7){
            this.dispose();
            ChestIsEmptyDialog chestIsEmptyDialog = new ChestIsEmptyDialog(null,true);
            chestIsEmptyDialog.setVisible(true);
        } else {
            this.dispose();
            if (Player.getInstance().getAgility() < 4){
                Player.getInstance().setHp(0);
                MimicKilledYouInstantly mimicKilledYouInstantly = new MimicKilledYouInstantly(null, true);
                mimicKilledYouInstantly.setVisible(true);
            } else {
                GUIandLogicIntermediary.handleMimicEncounter();
            }
        }
    }//GEN-LAST:event_openChestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chestFoundLabel;
    private javax.swing.JPanel chestFoundPanel;
    private javax.swing.JLabel chestIconLabel;
    private javax.swing.JButton openChestButton;
    private javax.swing.JButton passChestButton;
    // End of variables declaration//GEN-END:variables
}